name: Create EC2 Instance

on:
  workflow_dispatch:

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install or Update AWS CLI
        run: |
          # Download the AWS CLI v2 installer
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          # Install unzip utility
          sudo apt update && sudo apt install unzip -y
          # Unzip the installer
          unzip awscliv2.zip
          # Install or update AWS CLI
          sudo ./aws/install --update
          # Verify installation
          aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          # Launch an EC2 instance and capture the instance ID
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-00bb6a80f01f03502 \
            --count 1 \
            --instance-type t2.micro \
            --key-name momo \
            --security-group-ids sg-098abba7dbf67b15c \
            --subnet-id subnet-06ff5526352692bbc \
            --query 'Instances[0].InstanceId' \
            --output text)

          # Check if the instance ID was captured
          if [ "$INSTANCE_ID" == "None" ]; then
            echo "Failed to launch EC2 instance."
            exit 1
          fi

          echo "EC2 Instance created with ID: $INSTANCE_ID"

      - name: Tag the Instance
        run: |
          if [ -z "$INSTANCE_ID" ]; then
            echo "No instance ID found. Skipping tag creation."
            exit 1
          fi
          aws ec2 create-tags \
            --resources $INSTANCE_ID \
            --tags Key=Name,Value=GitHubActionsInstance
